//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculoIndice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int CalificacionId { get; set; }
        public Nullable<int> EstudiantesId { get; set; }
        public Nullable<int> AsignaturaId { get; set; }
        public string Calificación { get; set; }
        public Nullable<int> Promedio { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
